name: vercel 배포
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4
      - name: Node 설치
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: 시크릿 파일들 추가하기
        run: echo "${{ secrets.ENV }}" > .env


      - name: 의존성 라이브러리 설치
        run: npm ci

      - name: supabase 환경 setup
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: db 타입 생성
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: npx supabase gen types typescript --project-id ${{ secrets.SUPABASE_PROJECT_ID }} > ./src/types/database.types.ts

      - name: vercel cli 설치
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}